# Generated by Django 5.0 on 2023-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('age', models.PositiveIntegerField(default=1, verbose_name='Возраст')),
                ('gender', models.BooleanField(verbose_name='Гендер')),
                ('birthDay', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Человека',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
