# Generated by Django 5.0 on 2023-12-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0002_news_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='popular',
            field=models.CharField(default='НЕТ', max_length=3, verbose_name='Сделать популярным? ДА или НЕТ'),
        ),
    ]
