# Generated by Django 5.0 on 2023-12-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0004_news_commentarij_news_email_news_like_news_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='email',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='password',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
