# Generated by Django 5.0 on 2023-12-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0005_alter_news_email_alter_news_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='commentarij',
            field=models.CharField(default='None', max_length=50, verbose_name='добавить комментарий?'),
        ),
    ]
