# Generated by Django 5.0 on 2023-12-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0006_alter_news_commentarij'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='commentarij',
            field=models.CharField(max_length=50, verbose_name='добавить комментарий?'),
        ),
    ]
