# Generated by Django 5.0 on 2023-12-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0008_alter_news_commentarij'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='None', max_length=20)),
                ('password', models.CharField(default='None', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='email',
        ),
        migrations.RemoveField(
            model_name='news',
            name='password',
        ),
    ]
