# Generated by Django 5.0 on 2023-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadanie', '0009_person_remove_news_email_remove_news_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentarij', models.CharField(default='None', max_length=50)),
                ('like', models.CharField(default='0', max_length=3, verbose_name='добавить лайки?')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='commentarij',
        ),
        migrations.RemoveField(
            model_name='news',
            name='like',
        ),
    ]
